# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
    # this one may change README.Rmd and thus must run before
    # readme-rmd-rendered
    -   id: end-of-file-fixer
        exclude: '\.Rd'
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9020
    hooks:
    -   id: roxygenize
        additional_dependencies:
        - dplyr
        - ggplot2
        - ggforce
    -   id: use-tidy-description
    -   id: spell-check
        args: [--lang=en_GB, --read-only]
        exclude: >
          (?x)^(
          .*\.jpeg|
          .*\.pdf|
          .*\.png|
          .*\.RData|
          .*\.rds|
          .*\.Rds|
          .*\.Rproj|
          (.*/|)\.gitignore|
          (.*/|)\.pre-commit-.*|
          (.*/|)\.Rbuildignore|
          (.*/|)NAMESPACE|
          LICENSE.*|
          DESCRIPTION|
          (.*/|)WORDLIST|
          \.github/workflows/.*|
          R/.*|
          data/.*|
          tests/.*|
          man/piano-package.Rd|
          )$
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: no-print-statement
    -   id: no-debug-statement
    -   id: deps-in-desc
    -   id: pkgdown
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.(Rhistory|RData|Rds|rds)$'
        # `exclude: <regex>` to allow committing specific files

ci:
    autoupdate_schedule: monthly
    skip: [pkgdown]
